# Generated by Django 3.1.3 on 2023-07-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='choice_content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_grade',
            new_name='grade_weight',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='choices',
            new_name='chocies',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
